### ISSUE TITLE
BIDS convention for labels

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/bavaria-quebec#13]
A suggestion for naming lesion segmentation files would be the one used in the lab: https://github.com/ivadomed/ivadomed/wiki/repositories#derivatives

example: `derivatives/labels/sub-m012474/ses-20080925/sub-m012474_ses-20080925_acq-ax_lesion-manual.nii.gz`

The JSON file would include author and date, eg:
~~~
{
    "Author": "Bob Dylan",
    "Date": "2020-07-29 21:25:37"
} 
~~~

Additional info from BIDS:
- https://groups.google.com/g/bids-discussion/c/uR6Wbp26vBM/m/yQrgLYElAQAJ?utm_medium=email&utm_source=footer&pli=1

**Comment by jqmcginnis** [comment]
We also asked the [BIDS mailing list](https://groups.google.com/g/bids-discussion/c/NkGyChD2QY4/m/p8qXjtWcBAAJ) some time ago, receiving two recommendations ( I copy / paste the relevant sections for easier referencing):

(I) Option 1:

    `sub-123456_ses-20220101_dseg.nii.gz`

specify in the json file:

    `"Manual": "true" `

See this [table](https://bids-specification.readthedocs.io/en/latest/05-derivatives/03-imaging.html#common-image-derived-labels) for the lesion label you can use:

(II) Option 2:

Another possibility if those [are] just binary masks, you can also use the [derivative specification](https://bids-specification.readthedocs.io/en/latest/05-derivatives/03-imaging.html#masks) for those:

    `sub-123456_ses-20220101-label-lesionsAxManual_mask.nii.gz`

and specify in the json file:

    "Type": "Lesion"
    
**Conclusion:**

Looking into the different conventions, I actually prefer the one @jcohenadad and his lab have been using for the following reasons:
 
 (I) we don't have to look into the json in order to identify if it's a manual lesion
 (II) the label "lesion" seems more descriptive in comparison to using "dseg"
