### ISSUE TITLE
make sure lesion segmentation output are encoded as FLOAT

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/bavaria-quebec#9]
referring to:

https://github.com/sct-pipeline/bavaria-quebec/blob/15d62f2f9465cebdc9bea3a5dd3184cef7bc5f5e/source/pipeline/spinal_cord/preprocess_raw_dataset.sh#L92

our goal is to have stitched lesion masks that are encoded between 0 and 1 as float, in case lesion in chunk1 is not perfectly overlapping with lesion in chunk2.

**Comment by jqmcginnis** [comment]
To ensure that the lesion masks are in the correct value range {0,1} and encoded as float, we convert the lesion mask before we actually stitch them, c.f. 834ee5e (or relevant code snipped below):

```
for i in "${ax_lesion_files[@]}"
do
   sct_image -i $i -type float32 -o $i
   sct_maths -i $i -bin 1e-12 -o $i
done
```
Due to the resampling function in the [stitching code](https://github.com/biomedia-mira/stitching/blob/master/stitching/src/main.cpp), we obtain non-binary values {0,.., 1} when stitching the masks, as these are interpolated in non-aligned grids, as we are using the origin and spacing of the NIFTI headers. The output of the stitched mask is indeed float, as implemented in the [stitching c++ module](https://github.com/biomedia-mira/stitching/blob/master/stitching/src/main.cpp), c.f. relevant code below:

```
target = subimage(target, 0, 0, off_z_min, target.sizeX(), target.sizeY(), off_z_max - off_z_min).clone();

target.dataType(mia::FLOAT);
itkio::save(target, filename_out);
```
Thus, there is no need to convert the stitched lesion masks to FLOAT.

Feel free to close @jcohenadad if you feel this has been properly addressed.
